# This file is used to store the configuration of the site.

title: "SimpleWiki"
description: "A simple Jekyll wiki theme"

url: "https://riblanc.github.io"
baseurl: "/simple-wiki"
repository: riblanc/simple-wiki

# Theme settings
breadcrumb_separator: "»"
breadcrumb_font_size: 1.25rem

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-github-metadata

collections_dir: ./wiki

collections:
  dummy:
    output: true
    directory: ./wiki/_dummy
    permalink: /wiki/:path/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: "text"

google:
  cx: 4661cb6c6e7f44632
  site_verification: EqtKYUkYs-JttF6_8XsoKWZod8Qc2F4jvv3krniYebE
