name: Jekyll site CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      # Install Jekyll and dependencies
      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # Build the site with your custom plugin
      - name: Build the site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build


      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mv _site public 
          git add public
          git commit -a -m "Build and deploy Jekyll site"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true

